### ISSUE TITLE
spells question

### ISSUE THREAD

**Issue by emil92b** [soul4soul/ot-monster-converter#64]
so i have a few questions regarding some spells that didn't seem to work

using the CipMon > TfsRev for 1.5

currently it will make you invisible instead of monster / item
`{name = "outfit", interval = 2000, chance = 17, monster = "rabbit", duration = 20000, range = 7, target = true, effect = CONST_ME_MAGIC_BLUE}`

was it intentional that "min" should be higher than "max" or an error?
also i'm not sure how it should be working for paralyze/haste values, do i need to double the values or do you know the formula, coz it feels very weak right now using them on higher version than original 7.7
`{name = "speed", interval = 2000, chance = 13, speed = {min = -100, max = -80}, duration = 25000, range = 7, target = true, shootEffect = CONST_ANI_POISON, effect = CONST_ME_POISONAREA},`

i know this converter warned that it wasn't supporting it yet, but do you knw any other workaround?
`{name = "drunk", interval = 2000, chance = 20, drunkenness = 60, duration = 30000, range = 7, target = true, shootEffect = CONST_ANI_ENERGY, effect = CONST_ME_TELEPORT},`

also good job on the converter besides this i haven't had any issues, much appreciated!

**Comment by soul4soul** [comment]
1. Looks to be an assumption on my side the feature worked and a shortcoming in TFS revscriptsys. I don't see anyway to set outfits correctly from TFS revscriptsys. The lua part (data\scripts\lib\register_monster_type.lua between lines 280 and 335) doesn't read in a field named "monster" or "item". The cpp part only looks at the field called outfit and doesn't look like it will handle the difference between item and monster name correctly (src\monsters.cpp lines 708 to 717, for reference in the same file lines 390 to 413 is how xml does it)
2. min/max are sometimes wrong because I forgot that negative values they have to be switched.  As for the strength of the speed change I might be missing a 120 offset. I see I applied the offset to the monsters base speed but not their spells.
3. The warning is only in regards to drunkenness strength, the spell still works but strength is hard coded to 60 during conversion. TFS only recently introduced a concept of drunkenneess strength with values 0 to 100, most monsters in the TFS pack don't even use the strength field.  It's not clear how cipbia drunkenness relates to TFS drunkenness. You could try asking @Kay on otland.

**Comment by soul4soul** [comment]
> how will you apply the offset to `Speed (-90, 10, 25)` ? just adding 120 to base or whats your thought
Yes adding 120 to base.

> also i noticed that `Strength` skill reducing spell was missing https://github.com/soul4soul/ot-monster-converter/blob/master/app/MonsterConverterCipMon/CipMonConverter.cs#L459-L464
> 
> id like to share with you from my tests, i know tfs might be lacking some code for this, but leaving this here anyway `Strength (skill, base %, variation, duration * 1000)`
> 
> skill: 1 = "fist, club, sword, axe", 2 = "distance", 3 = "fist, club, sword, axe, distance", 5 = "fist, club, sword, axe, shielding"

Yeah TFS only supports that type of spell using a script so the converter can't handle it. I can improve the error message so it prints out that information. At least it only occurs 11 times which isn't to many to convert by hand. You will need something like the spells in data\spells\scripts\monster\*_skill_reducer.lua in the TFS repo.
![image](https://user-images.githubusercontent.com/5142635/148306517-8ca59892-5048-4cab-bc93-159870a6888d.png)

I opened a PR based on the info in this issue.

**Comment by emil92b** [comment]
nah the chance is whats after the colon, each monster have different skills they reduce from the player, there was also something about not reducing skill below 0 or 10, cant remember tho

**Comment by soul4soul** [comment]
> nah the chance is whats after the colon, each monster have different skills they reduce from the player, there was also something about not reducing skill below 0 or 10, cant remember tho

My guess is you can't go below skill level 10 as that is the base skill level on cipbia.

**Comment by soul4soul** [comment]
Those numbers look like bit flags
001 (1) - All melee skills 
010 (2) - Distance skill
100 (4) - Shielding skill
