### ISSUE TITLE
missing things and suggestion to improve the "cipsoft" converter

### ISSUE THREAD

**Issue by emil92b** [soul4soul/ot-monster-converter#76]
_imo dont adapt to TFS, it should adapt to your converter! for example use cipsoft chance values for everything, that means base speed, loot, spells etc. makes more sense to change the formula in tfs based on the correct values instead._

- monsters have some of their "outfit" and "invisible" spells converted to attacks rather than defense and vice versa

- haste/paralyze speed spells should use "base" and "variation"

- demon/illusion name for register

- missing space in some summon names

- voice should not convert "interval" and "chance" instead use a formula in tfs, also minotaur mage "#W" should be yell = true

- flamethrower, magicthrower, plaguethrower, shredderthrower should have item lookTypeEx = 0

- monsters that are convincable is missing summonCost value

- monster melee condition auto attacks

- target strategy values (closest, weakest, strongest, random)

- monster training [https://otland.net/threads/7-7-realots-7-7-cipsoft-files-virgin.244562/page-57#post-2685321](https://otland.net/threads/7-7-realots-7-7-cipsoft-files-virgin.244562/page-57#post-2685321)

**Comment by soul4soul** [comment]
I don't understand your first paragraph but I addressed each bullet point below.

>     * monsters have some of their "outfit" and "invisible" spells converted to attacks rather than defense and vice versa
>     * missing space in some summon names
>     * monsters that are convincable is missing summonCost value

I will fix these issues.

>     * voice should not convert "interval" and "chance" instead use a formula in tfs, also minotaur mage "#W" should be yell = true
#W = whisper but TFS only has yell true/false, so I set it to not yell as the closest option. I didn't log a warning because its so trivial but I could add that.
 
>     * haste/paralyze speed spells should use "base" and "variation"
They do but I haven't made a new release yet.

>     * demon/illusion name for register
idk what you mean for this bullet, both the regular demon and illusion demon are parsed.

>     * flamethrower, magicthrower, plaguethrower, shredderthrower should have item lookTypeEx = 0
TFS doesn't support that, when lookTypeEx is 0 the monster sparkles -- kinda weird on TFS part.

>     * monster melee condition auto attacks

Yes this is missing, I don't know how to get this information from the mon files. Do you know?

>     * target strategy values (closest, weakest, strongest, random) 

This is parsed but none of the supported output formats support this information.

>     * monster training https://otland.net/threads/7-7-realots-7-7-cipsoft-files-virgin.244562/page-57#post-2685321

This isn't parsed because none of the supported output formats support this information.

**Comment by soul4soul** [comment]
closed with #77
